### ISSUE TITLE
Missing early return in `def insert`?

### ISSUE THREAD

**Issue by mozjag** [seanchen1991/python-lru#1]
https://github.com/seanchen1991/python-lru/blob/5cd01b7f106d1c7a5efc03b7537db2f84a3d0789/src/lru_cache.py#L21-L42

When the key is already in storage, you can skip the capacity test and you don't want to `add_to_head` since you've already `touch`ed.

**Comment by seanchen1991** [comment]
Good point. Thanks for bringing it up!
